### PR TITLE
mainly updated info_url and comment_url to a fixed URL

### PR DESCRIPTION
**Pull request by LoveMyData**
https://morph.io/lovemydata/bankstown

### CODE REVIEW

**Comment by henare** [comment]
Thanks for the PR @LoveMyData.

I'm not really sure what this is fixing. In the existing scraper the more_info links seem fine, even on recent records (I checked council_reference DA-1140/2016 and it was OK). Can you tell me what I'm missing?

**Comment by LoveMyData** [comment]
infoURL and commentURL are no longer working. I think they have an expire timer on the web site. so whatever link in the database, it will expires after a while

**Comment by henare** [comment]
The most recently scraped DA in the [production scraper](https://morph.io/planningalerts-scrapers/bankstown) is DA-1140/2016. Its info_url and comment_url are set to:

http://eplanning.bankstown.nsw.gov.au/ApplicationSearch/ApplicationDetails?applicationId=77494379

...which works fine for me so I'm still not seeing the problem we're trying to fix here.

**Comment by LoveMyData** [comment]
Try some older links like 10 days ago on 16/11/2016

http://eplanning.bankstown.nsw.gov.au/ApplicationSearch/ApplicationDetails?applicationId=76420854

**Comment by henare** [comment]
Yeah that's pretty rubbish. I'll merge this.

**Pull request merged**
